run:
  concurrency: 4
  timeout: 5m
  tests: false
  allow-parallel-runners: true
  go: '1.18'
  skip-dirs:
    - lib/
linters:
  enable:
    - errorlint
    - govet
  disable:
    - gosimple
    - ineffassign
    - staticcheck
