version: "2"

run:
  concurrency: 4
  timeout: 5m
  tests: true
  allow-parallel-runners: true
  go: '1.25'
linters:
  default: standard
  enable:
    - ginkgolinter
  disable:
    - ineffassign
    - staticcheck
issues:
  new: true
