{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: {{ template "ardoq-k8s-bridge.name" . }}
    chart: {{ template "ardoq-k8s-bridge.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "ardoq-k8s-bridge.fullname" . }}
rules:
  - verbs:
      - "get"
      - "list"
      - "watch"
    apiGroups:
      - ""
      - "apps"
    resources:
      - "deployments"
      - "statefulsets"
      - "nodes"
  - verbs:
      - "*"
    apiGroups:
      - "coordination.k8s.io"
    resources:
      - "leases"
  {{- end -}}