{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: {{ template "k8s-ardoq-bridge.name" . }}
    chart: {{ template "k8s-ardoq-bridge.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "k8s-ardoq-bridge.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "k8s-ardoq-bridge.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "k8s-ardoq-bridge.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
  {{- end -}}
