{{- if and (.Values.metrics.enabled) (.Values.metrics.serviceMonitor.enabled)}}
kind: ServiceMonitor
apiVersion: monitoring.coreos.com/v1
metadata:
  name: {{ include "k8s-ardoq-bridge.fullname" . }}
  labels:
    {{- include "k8s-ardoq-bridge.labels" . | nindent 4 }}
spec:
  endpoints:
    - honorLabels: true
      interval: 30s
      path: /metrics
      port: http
      scheme: http
      scrapeTimeout: 10s
  selector:
    matchLabels:
      {{- include "k8s-ardoq-bridge.labels" . | nindent 6 }}
{{- end }}
