---
# This is a manually triggered workflow to package and upload the Helm chart from the
name: Publish Helm chart

on:
  workflow_dispatch:
    inputs:
      ref:
        description: The branch, tag or SHA to publish.
        required: true
env:
  HELM_REP: k8s-ardoq-bridge
  GH_OWNER: ardoq
  CHART_DIR: chart
  KIND_VERSION: "v0.11.1"
jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.ref }}
          fetch-depth: 0
      - name: Configure Git
        run: |
          git config --global user.name "$GITHUB_ACTOR"
          git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Install Helm
        uses: azure/setup-helm@v1.1
        with:
          version: v3.7.2
      - name: Set up python
        uses: actions/setup-python@v2.3.1
        with:
          python-version: 3.7
      - name: Setup Chart Linting
        id: lint
        uses: helm/chart-testing-action@v2.2.0
#      - name: Setup Kubernetes cluster (KIND)
#        uses: helm/kind-action@v1.2.0
#        with:
#          version: ${{ env.KIND_VERSION }}
#          cluster_name: kind-test
#      - name: Test connection to Kubernetes cluster
#        run: |
#          kubectl cluster-info
#          kubectl wait --for=condition=Ready nodes --all --timeout=300s
#          kubectl describe node
      - name: Run chart-testing
        run: ct lint --validate-maintainers=false --charts ${{ env.CHART_DIR }}

      - name: Install chart-releaser
        run: |
          wget https://github.com/helm/chart-releaser/releases/download/v1.3.0/chart-releaser_1.3.0_linux_amd64.tar.gz
          echo "baed2315a9bb799efb71d512c5198a2a3b8dcd139d7f22f878777cffcd649a37  chart-releaser_1.3.0_linux_amd64.tar.gz" | sha256sum -c -
          tar xzvf chart-releaser_1.3.0_linux_amd64.tar.gz cr
      - name: Package helm chart
        run: |
          ./cr package ${{ env.CHART_DIR }}
      - name: Upload helm chart
        # Failed with upload the same version: https://github.com/helm/chart-releaser/issues/101
        continue-on-error: true
        run: |
          ./cr upload -o ${{ env.GH_OWNER }} -r ${{ env.HELM_REP }}
        env:
          CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Index helm chart
        run: |
          ./cr index -o ${{ env.GH_OWNER }} -r ${{ env.HELM_REP }} -c https://raw.githubusercontent.com/${{ env.GH_OWNER }}/${{ env.HELM_REP }}/gh-pages/ -i index.yaml --push
        env:
          CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
